CREATE DATABASE IF NOT EXISTS college
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE college;

CREATE TABLE IF NOT EXISTS complaints (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(25) NOT NULL,
  category VARCHAR(60) NOT NULL,
  location VARCHAR(120) NOT NULL,
  priority VARCHAR(20) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
